### ISSUE TITLE
Strange demo:tables behavior

### ISSUE THREAD

**Issue by lasfin** [basisjs/basisjs#47]
http://basisjs.com/basisjs/demo/defile/table.html
'test remove/add to document' and 'test display none/block' buttons does nothing, except adding 'xx' to table first tr child.
Is it expected behavior?

**Comment by lahmatiy** [comment]
Yep, it's expected behaviour:
- 'test remove/add to document' button removes table element from document and adds it back
- 'test display none/block' sets 'display:none' to table element and than remove `display` value
Operations perform in single code frame, so changes aren't visible. Since just one draw that draws the same as before operations. That's why `xx` adds to one of cell – to see something was changed.
Those tests are needed to check that layout is not broken after table become visible again. Because those tests are for ScrollTable instance that has fixed header and scrolling body. It's require additional layout tricks that may break on table manipulations.
