### ISSUE TITLE
Why itemsChanged trigger many times?

### ISSUE THREAD

**Issue by Mavrin** [basisjs/basisjs#48]
Hi!
When entity is synchronise https://github.com/Mavrin/tpmobile/blob/master/tests/spec/view.js#L21 itemsChanged trigger many times https://github.com/Mavrin/tpmobile/blob/master/tests/spec/view.js#L21
Is it correct behaviour?

**Comment by lahmatiy** [comment]
That's because `readList()` creates new entity type instances one by one. When entity is creating it adding to `Type.all`. Usually bulk methods (like `setAndDestroyRemoved()` method) switch on event aggregation and flush collected events when all operations done. But `readList()` method doesn't do this. For now you can try:

```js
var Dataset = require('basis.data').Dataset.setAccumulateState;
...

setAccumulateState(true);
this.setAndDestroyRemoved(View.readList(views));
setAccumulateState(false);
```

I think it was wrong decision about `readList()` to return array of entity type instances rather than normalized objects (just processed through `read()` method). Probably we should change its behaviour or wrap instances creation by `setAccumulateState()`.

**Comment by Mavrin** [comment]
Thank you for good explanation.
